### ISSUE TITLE
Bug: 3.0 - IFCW - offers invalid IF based on data selected 

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1671] opened 2015-02-24 07:13 UTC
# problem
the IFCW offers an invalid IF option for flood polygon impact on building polygons
data are Jakarta flood 2013; attribute affected = 1 & OSM jakarta buildings

![image](https://cloud.githubusercontent.com/assets/5743135/6344755/bbc8d808-bc2f-11e4-9eb9-5070f8e9681c.png)

# proposed solution
Flood Native Polygon Experimental Function is the correct option for this data combination- I think.
Flood Building Impact Function - should only be available if hazard data are a raster - see logic below

If I select Flood Building Impact Function I get offered the option to change the threshold parameter. This is something i would set if the hazard data were a flood raster or a polygon data set with a depth attribute (not currently used).

![image](https://cloud.githubusercontent.com/assets/5743135/6344793/4b8c5c12-bc30-11e4-9bd5-c076c07aa740.png)

**Comment by akbargumbira** [comment] 2015-02-28 12:03
Hi @Charlotte-Morgan, actually Flood Building Impact Function will also work with polygon hazard. The problem is that it can not differentiate what option should be given to each type of the hazard (i.e when we have polygon hazard, user will still see that threshold option, even when the IF does not use it).

This is a case of my concern here https://github.com/AIFDR/inasafe/issues/1099, almost a year ago, (Issues in Parameter of Impact Function). This is also a problem with other IFs (e.g Volcano IF, when we have polygon hazard zone, user is given the radii options). For Volcano IF I have made a separated issue #1666  (Optimise volcano on building IF and separate them into 2 between point and polygon hazard).

I will make sure this is covered when we review all the IFs!

**Comment by cchristelis** [comment] 2015-03-12 10:46
Hi @Jannes123, it looks like this issue is related to the #1689. It might be good to chat with @akbargumbira at some point.

**Comment by akbargumbira** [comment] 2015-06-10 03:57
This is resolved. I am closing this

**Closed by akbargumbira** 2015-06-10 03:57 UTC
Labels: Ready
