### ISSUE TITLE
Volcano IF running error on windows

### ISSUE THREAD

**Issue by mahardika** [AIFDR/inasafe#1541] opened 2015-01-29 08:30 UTC
# Problem 

Takes long time to run volcano analysis and error message's show up (see below) with no result analysis.

Processing started

Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of volcano_try on people .

The following postprocessors will be used:

Gender: Calculates gender related statistics.
Age: Calculates age related statistics.
Minimum needs: Aggregates minimum needs.
Checking available memory

Computed cellsize was None. Memory check currently only works for raster input layers.
Preparing hazard data

We are resampling and clipping the hazard layer to match the intersection of the exposure layer and the current view extents.

Preparing exposure data

We are resampling and clipping the exposure layer to match the intersection of the hazard layer and the current view extents.

Preparing aggregation layer

We are clipping the aggregation layer to match the intersection of the hazard and exposure layer extents.

Problem

The following problem(s) were encountered whilst running the analysis.

ReadLayerError
Suggestion

You can try the following to resolve the issue:

Only point, line and polygon geometries are supported. Geometry type in filename c:\users\fadmam\appdata\local\temp\inasafe\2015-01-29\fadmam\work\clip_dko7xf.shp was 4.
Details

These additional details were reported when the problem occurred.

An exception occurred when setting up the model runner.
Only point, line and polygon geometries are supported. Geometry type in filename c:\users\fadmam\appdata\local\temp\inasafe\2015-01-29\fadmam\work\clip_dko7xf.shp was 4.
Diagnostics (click for details)

In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\analysis.py", line 965, in run_analysis self.runner = self.impact_calculator.get_runner()
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\impact_calculator.py", line 186, in get_runner hazard_layer = self.hazard_layer()
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\impact_calculator.py", line 121, in hazard_layer return self._get_layer(self._hazardLayer)
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\impact_calculator.py", line 83, in _get_layer return convert_to_safe_layer(layer)
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\gis.py", line 368, in convert_to_safe_layer return safe_read_layer(layer.source())
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\storage\core.py", line 28, in read_layer return Vector(filename)
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\storage\vector.py", line 161, in __init__ self.read_from_file(data)
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\storage\vector.py", line 519, in read_from_file raise ReadLayerError(msg)

# Platform 
windows 7  64 bit
QGIS 2.6
InaSAFE 3.0.0.dev-master

# Analysis 
- exposure : people popmap10_all.tif
- hazard : volcano_smithsonian.shp

p.s I have tried to clip the analysis area into smaller, but it still takes forever to run the analysis. I have tried to run the analysis only for one volcano, but the error massage still showed up.

**Comment by ismailsunni** [comment] 2015-01-29 08:34
Hi @mahardika 

Based on the error, 
```
Only point, line and polygon geometries are supported. Geometry type in filename c:\users\fadmam\appdata\local\temp\inasafe\2015-01-29\fadmam\work\clip_dko7xf.shp was 4.
Diagnostics (click for details)
```

It seems the layers are not a point, line, or polygon layer. Perhaps multipoint, multiline, or multipolygon. Can you check it?

**Comment by mahardika** [comment] 2015-01-29 08:35
yup. will check it now

**Comment by mahardika** [comment] 2015-01-29 08:49
I was trying to analyse Mt Marapi (Sumatra) only. And the error message still showed up : 

Processing started

Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of volcano_try on people .

The following postprocessors will be used:

Gender: Calculates gender related statistics.
Age: Calculates age related statistics.
Minimum needs: Aggregates minimum needs.
Problem

The following problem(s) were encountered whilst running the analysis.

InsufficientOverlapError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

A problem was encountered when trying to determine the analysis extents.
There was insufficient overlap between the input layers and / or the layers and the viewable area. Please select two overlapping layers and zoom or pan to them or disable viewable area clipping in the options dialog. Full details follow:
Failed to obtain the optimal extent given:

Hazard: C:/Users/fadmam/Desktop/socialization/volcano_try.shp
Exposure: C:/Users/fadmam/Desktop/socialization/popmap10_all.tif
Viewable area Geo Extent: [101.799338, -3.012315, 102.40403, -2.629272]
Hazard Geo Extent: [100.4733333, -0.380555556, 100.4733333, -0.380555556]
Exposure Geo Extent: [95.05902541031102, -10.997474511110997, 141.00718741031102, 5.907682588889002]
Viewable area clipping enabled: True
Details: Bounding boxes of hazard data, exposure data and viewport did not overlap, so no computation was done. Please make sure you pan to where the data is and that hazard and exposure data overlaps.
Diagnostics (click for details)

In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\gui\widgets\dock.py", line 1019, in accept self.analysis.setup_analysis()
In file "C:/Users/fadmam/.qgis2/python/plugins\inasafe-develop\safe\utilities\analysis.py", line 690, in setup_analysis raise e

**Comment by ismailsunni** [comment] 2015-01-29 08:56
Perhaps @timlinux remember this.

Since we clip first before make the buffer for the hazard zone of volcano point, there is a possibility that makes insufficient overlap.

I need to dig through the issues to check whether we have fixed this or not.

or may be @akbargumbira also remember?

**Comment by akbargumbira** [comment] 2015-01-29 13:03
No. See my comment here https://github.com/AIFDR/inasafe/issues/928

>Ha! I found the underlying issue here. @timlinux: We don't clip the exposure layer if the hazard layer is point data. I am surprised that for processing Java Population exposure, it is fast enough. Of course it will run forever for all Indonesia Population

**Comment by akbargumbira** [comment] 2015-01-29 13:09
I see that @mahardika is using popmap world. For now @mahardika, please use a smaller population data e.g using popmap clipped to java only.

**Comment by akbargumbira** [comment] 2015-01-31 23:07
This is a duplicate of #928. Closing this

**Closed by akbargumbira** 2015-01-31 23:07 UTC
