### ISSUE TITLE
Python Error - InaSAFE-Dev

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1507] opened 2015-01-14 10:38 UTC
# problem
the following python error window appears when opening QGIS

Couldn't load plugin inasafe-dev due an error when calling its classFactory() method

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 208, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev__init__.py", line 36, in classFactory
    from plugin import Plugin
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 460, in import
    mod = builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\plugin.py", line 24, in 
    from safe.utilities.keyword_io import KeywordIO
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe__init.py", line 25, in 
    from safe.common.exceptions import TranslationLoadError
ImportError: cannot import name TranslationLoadError

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.6.0-Brighton Brighton, exported

Python path: ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\Program Files (x86)\ArcGIS\Desktop10.2\bin', 'C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy', 'C:\Program Files (x86)\ArcGIS\Desktop10.2\ArcToolbox', 'C:\PROGRA~1\QGISBR~1\bin\python27.zip', 'C:\PROGRA~1\QGISBR~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISBR~1\bin', 'C:\PROGRA~1\QGISBR~1\apps\Python27', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', 'C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe', 'C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras', 'C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev', 'C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe_extras\parameters']

# environment
windows
QGIS 2.6
InaSAFE 3.0

**Comment by akbargumbira** [comment] 2015-01-18 00:40
Hi @Charlotte-Morgan, how did you get this? I could not replicate this

**Comment by timlinux** [comment] 2015-01-26 12:49
Hi

This is because you have both InaSAFE and inasafe-dev in your python path:

```
'C:\Users\AIFDR_ADMIN.qgis2\python\plugins\inasafe', 
'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev', 'C:\Users\AIFDR_ADMIN.qgis2\python\plugins\inasafe-dev\safe_extras\parameters']
```

Since we change the package layout the exception class is now in safe/common etc where before it was in safe_qgis somewhere. So the problem is that when QGIS scans the plugins to see which are available, if the __init__.py references package internals they will occupy the same namespace (the namespacing starts from below the plugin folder. So python has already loaded the package from 

```
'C:\Users\AIFDR_ADMIN.qgis2\python\plugins\inasafe', 
```

Then it comes along to see if 

```
'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev', 
```
is a valid plugin and tries to reference stuff in a module loaded from the inasafe plugin. I fixed this in my safe_refactor branch here:

https://github.com/timlinux/inasafe/commit/7d338e46fefd4ba1efa7341a13d45edd9937c790 

The fix is to NOT LOAD ANYTHING in the __initi__.py - just let QGIS know you are here and available, and if QGIS really wants to load the plugin it will call the classFactory from which point you can start importing package internals etc.

Unfortunately while we still have old and new API togetehr in the same system there is no immediate fix for your problem so I am going to close this. Once we have 3 being stable and 3.1 being the newcomer we should not see this anymore.

Apologies if the explanation was a bit wordy :-)

**Closed by timlinux** 2015-01-26 12:49 UTC
Labels: Ready, Release Blocker
