### ISSUE TITLE
InaSAFE minimum needs result problem

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1441] opened 2014-12-10 08:32 UTC
# Problem 
InaSAFE minimum needs produce different result from total minimum needs compared to minimum needs based on aggregation. 

# Detail
We got email from Elida that she ask about the different result from minimum needs from total minimum needs compared with detailed minimum needs. 

**Total result minimum needs:** 
![image](https://cloud.githubusercontent.com/assets/2520159/5372702/c6c6a2da-807f-11e4-8890-ae9e49c4e132.png)

**Detailed minimum needs:**
![image](https://cloud.githubusercontent.com/assets/2520159/5372737/74c35b26-8080-11e4-873c-a917c88dc0d1.png)

From the 2 images above, there are huge different number for detailed minimum need, for example **Rice** in total minimum needs only need 140kg but when i looked at detailed minimum needs, it become 15.935kg and it also affect for other needs such as family kits, toilet, drinking water, and clean water.

# Platform
We're using 2 devices to make sure the problem are not the computer problem.

First device run using:
QGIS 2.4
InaSAFE 2.1
Windows 7

Second device run using:
QGIS 2.6
InaSAFE 2.2
Windows 7

**Comment by akbargumbira** [comment] 2015-01-07 09:59
From Elida's email,  this difference is because the first table calculates minimum needs based on evacuated people, but in the postprocessor, it calculates based on affected people.

**Comment by ismailsunni** [comment] 2015-01-13 10:51
This is quite easy to fix, actually.

So, it's true what Elida's said.

Therefore, the solution, we should choose, which one we want to use to calculate minimum needs. Is it `evacuated people` or `affected people`. This question is for @Charlotte-Morgan (but perhaps @timlinux or @akbargumbira can give some suggestions)

But, still, there will be slight difference between the total and the detailed one. Since we round up the total affected or evacuated people. And this is normal for me.

I don't really want to round up the detailed one (we will add rounded numbers, and it will give more difference with the total one).

**Comment by ismailsunni** [comment] 2015-01-27 07:32
Now, we use evacuated for minimum needs based on aggregation. See below:
![people_affected_by_flood_prone_areas_table-page-001](https://cloud.githubusercontent.com/assets/1421861/5914932/c693a28c-a630-11e4-9fb5-6496c9862471.jpg)
![people_affected_by_flood_prone_areas_table-page-002](https://cloud.githubusercontent.com/assets/1421861/5914959/1bc7f42e-a631-11e4-88f3-1c04f4674c88.jpg)

I will make sure the related unit tests are passing and commit the fix.

**Comment by akbargumbira** [comment] 2015-01-27 08:18
This issue is more philosophical and need to be standardized with all other IFs. 

Let's say we agree with calculating minimum needs for evacuated people (makes more sense, not all affected people need minimum needs). The problem is, most of other IFs (if not all) use affected people to calculate the minimum needs as they don't use any evacuation threshold variable to identify the number of people needing evacuation from the affected number.

The IF for flood raster on population is also misleading if we want to differentiate between 'affected' and 'evacuated'. It only calculates the affected people, while the report tells us 'People needing evacuation' (I guess all other IFs have this inconsistency). And with all the variables on this IF also uses term like 'evacuated_people'.

Another small inconsisteny in this IF:
'People need evacuation if in the area identified as "Flood Prone"'. This should not be 'People need evacuation', but 'People are affected"

**Comment by akbargumbira** [comment] 2015-01-27 08:21
I also remember that @Charlotte-Morgan asking the reference for this 1% default for evacuated people. I think we should move this into a bigger issue when we review all IFs (or when we migrate the IFs using QGIS API)

**Comment by ismailsunni** [comment] 2015-01-27 09:33
Yes, I agree with you. That's what I thought when I make the fix also.

But, perhaps, for now, let's move step by step. It will need much time to review all IFs, discussion, make them consistent, and so on.

**Comment by timlinux** [comment] 2015-01-27 13:57
One thing to add - the summary table should clearly state that the minimum needs are based on affected or evacuated people.

**Comment by ismailsunni** [comment] 2015-01-28 00:58
I have added information like below:
![inasafe - google chrome_033](https://cloud.githubusercontent.com/assets/1421861/5930486/bd1e956c-a6c2-11e4-9240-e5171c1794be.png)

I hope it's enough.

**Comment by Charlotte-Morgan** [comment] 2015-01-28 03:21
I agree with all this. Is a review of IF, what they do and how they are documented a task I can assign to GA staff that are available to assist as from February.

Sent from my iPhone

On 28 Jan 2015, at 7:58 am, Ismail Sunni <notifications@github.com<mailto:notifications@github.com>> wrote:


I have added information like below:
[inasafe - google chrome_033]<https://cloud.githubusercontent.com/assets/1421861/5930486/bd1e956c-a6c2-11e4-9240-e5171c1794be.png>

I hope it's enough.

-
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1441#issuecomment-71761820>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Closed** 2015-01-30 14:20 UTC
Labels: Aggregation, In progress
