### ISSUE TITLE
Wizard window not resizeable

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1484] opened 2015-01-08 04:33 UTC
# Problem
Both InaSAFE Keyword Creation Wizard and InaSAFE Impact Function Centric Wizard is not resizeable when I open it in QGIS 2.6. 

# Screenshot
 
![wizard_01](https://cloud.githubusercontent.com/assets/2520159/5657894/d0dd3a48-9729-11e4-89fd-8883ec4fe594.png)

![wizard_02](https://cloud.githubusercontent.com/assets/2520159/5657901/e7f812e8-9729-11e4-8a9e-013854a25a0e.png)

# Platform

I'm using QGIS 2.6 with InaSAFE version 2.2.0 dev clone from github and with operating system Windows 7 64bit

@timlinux

**Comment by Charlotte-Morgan** [comment] 2015-01-09 07:56
in QGIS 2.4 - the wizard window is initially off the top of the screen but can be resized in length and width. it can only be repositioned once it extends the full screen height.

**Comment by adissadis** [comment] 2015-01-12 03:19
Im also try to run in QGIS 2.4 (my computer run 2 qgis, 2.4 and 2.6) and it's still not resizeable and i also cant resized it.

**Comment by adissadis** [comment] 2015-02-03 02:52
I'm sorry @timlinux it seems the problem still there. I already pull the latest update of InaSAFE and open the InaSAFE Keyword Creation Wizard and InaSAFE Impact Function Centric Wizard, but i can't rezise the window up and down. I only can resize it to left and right. If i want to close the wizard, i need to resize it to left or right in order to see the close window at the upper right.

Im using QGIS 2.6

![inasafe_5](https://cloud.githubusercontent.com/assets/2520159/6013641/46248210-ab8a-11e4-94ea-2ec2eb647467.png)

![inasafe_6](https://cloud.githubusercontent.com/assets/2520159/6013642/49b54a68-ab8a-11e4-9242-5abb3a63f1b7.png)

**Comment by borysiasty** [comment] 2015-02-03 09:45
I'll try to look at it later this week and in the worst case in the middle of the next week when I'm back home. Does it affect all windows machines?

**Comment by adissadis** [comment] 2015-02-03 09:56
i think it affect all windows machines because @akbargumbira and my friends also tried this

**Comment by akbargumbira** [comment] 2015-02-03 10:02
I actually managed to get it at the center of the screen (no dialog out off the screen) at the beginning loading this dialog. The problem is, when I drag/resize the dialog, the dialog jumps expanding the height..

**Comment by timlinux** [comment] 2015-03-23 12:56
This was fixed in 3.0 release. I am adding a further fix to allow resizing on hidpi screens.

**Closed** 2015-04-21 13:08 UTC
Labels: Bug, User Interface
