### ISSUE TITLE
QGIS 2.6 Error loading plugin - InaSAFE 2.2.3

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1517] opened 2015-01-17 02:38 UTC
# problem

Get the following error when attempting to load the latest InaSAFE release version

# error message
![image](https://cloud.githubusercontent.com/assets/5743135/5787327/adfa10e6-9e2c-11e4-925b-20dbfef58e6c.png)

# proposed solution
make it happy

# settings
windows
QGIS 2.6

**Comment by akbargumbira** [comment] 2015-01-18 00:36
Hi @Charlotte-Morgan, due to the major refactor, you can't really have both inasafe 3.0-dev and 2.2.3 installed.. I guess you still have the 3.0 dev?

**Comment by timlinux** [comment] 2015-03-11 08:23
I am closing this as the issue is not really an issue with InaSAFE, more a problem with local setup on your computer

**Closed** 2015-03-11 08:23 UTC
Labels: Governance and Rollout
