### ISSUE TITLE
Flood / Road impact function not working with attribute set by wizard

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1156] opened 2014-07-28 19:20 UTC
QGIS 2.4 for Mac (Kyngchaos build) , InaSAFE 2.1 from repo.

I am trying to run the impact function with a flood layer (http://www.haitidata.org/layers/cnigs.spatialdata:hti_hazardhydrology_rareflood_westdepartment_nathat_polygon_052 ) and a road layer downloaded from OSM with the InaSAFE downloader tool. I get the error below. I have a feeling it is because if I have set the "FLOODED" attribute with the new wizard where I selected which attribute to use as "wet/dry" and then I have put the string under the wet category. After looking at the code of the impact function, I also tried adding an integer attribute manually named "affected" and put it equal to 1 and it is not working either (keyword set with the wizard).

Bug report from InaSAFE:

Processing started

Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of hti_hazardhydrology_rareflood_westdepartment_nathat_polygon_052Polygon on Roads .

The following postprocessors will be used:

Road type: Calculates road types related statistics.
Checking available memory

Computed cellsize was None. Memory check currently only works for raster input layers.
Preparing aggregation layer

We are clipping the aggregation layer to match the intersection of the hazard and exposure layer extents.

Calculating impact

This may take a little while - we are computing the areas that will be impacted by the hazard and writing the result to a new layer.

Problem

The following problem(s) were encountered whilst running the analysis.

GetDataError
Suggestion

You can try the following to resolve the issue:

There are no objects in the hazard layer with "Affected value"='1'. Please check the value or use a different extent.
Details

These additional details were reported when the problem occurred.

An exception occurred when calculating the results. Calculation error encountered:
There are no objects in the hazard layer with "Affected value"='1'. Please check the value or use a different extent.
Diagnostics (click for details)

In file "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/utilities/impact_calculator_thread.py", line 186, in run check_integrity=self._check_integrity)
In file "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/safe_interface.py", line 537, in calculate_safe_impact check_integrity=check_integrity)
In file "/Users/viv/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 68, in calculate_impact F = impact_function.run(layers)
In file "/Users/viv/.qgis2/python/plugins/inasafe/safe/impact_functions/inundation/flood_polygon_roads.py", line 219, in run raise GetDataError(message)

**Comment by ismailsunni** [comment] 2015-06-18 01:00
Hi @borysiasty 

For the wizard, can we automatically set the CRS layer to ESPG 4326? See my solution for the problem in this comment : https://github.com/AIFDR/inasafe/issues/1184#issuecomment-52061290

**Comment by borysiasty** [comment] 2015-06-18 10:21
@ismailsunni: Do you mean to automatically export the layer to a new one? Sounds a bit complicated.
 - It could be a memory layer, but as far as I remember storing keywords for memory layers doesn't work well - all memory layers have the same uri, and the layer uri is the key in the keywords database.
- It could be a shapefile in /tmp directory, but exporting PG to SHP is a step backward... and even can damage long attribute names.
- It could be a permanent file in the same directory / permanent table in the same schema with _wgs84 prefix... but this way we need to explain the user from those unexpected new layers come ;) 

Isn't easier to just explain the layers must be in the same crs? As I understand, the layers don't need to be in wgs84, they just need to have the same crs.

**Comment by ismailsunni** [comment] 2015-06-23 07:09
After some thought, I think giving user message if his layers are not in the same crs is not good for InaSAFE, is a nice idea.
But, talking about history, we had a ticket to automatically set the CRS on the fly (a long time ago).

May be @timlinux can give some opinions about this.

**Comment by borysiasty** [comment] 2015-06-23 08:05
Oh, so does it work with OTFR enabled? If so, than enabling it will be easy. I thought the problem is some functions don't work even with OTFR enabled.

**Comment by ismailsunni** [comment] 2015-06-25 05:04
@borysiasty 
I am not sure about the answer of your question.
The thing that I did was reproject the layer, and then it works.
But, I tried to look again at the problem this morning, I got different error like I posted in #2065 

I am looking at the error in #2065, it has a good indication that it's failed when InaSAFE tried to write the impact layer. So, may be this issue is not relevant anymore, since this ticket happened before the impact layer writing step.

**Comment by ismailsunni** [comment] 2015-06-25 05:07
I just looked at the impact function code. And @timlinux has fixed a simillar issue in #1857 

@timlinux can you confirm that this issue (#1156) is the same as #1857? If yes, we can close this one.

**Comment by akbargumbira** [comment] 2015-06-25 05:31
Yes, IF can only deal with WGS84 now. The extent CRS field in the base
class is not used yet by the IF (not sure with Martin's changes converting
some native IFs to QGIS IFs recently)

On Thu, Jun 25, 2015 at 1:07 PM, Ismail Sunni <notifications@github.com>
wrote:

> I just looked at the impact function code. And @timlinux
> <https://github.com/timlinux> has fixed a simillar issue in #1857
> <https://github.com/AIFDR/inasafe/issues/1857>
>
> @timlinux <https://github.com/timlinux> can you confirm that this issue (
> #1156 <https://github.com/AIFDR/inasafe/issues/1156>) is the same as #1857
> <https://github.com/AIFDR/inasafe/issues/1857>? If yes, we can close this
> one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe/issues/1156#issuecomment-115107285>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by ismailsunni** [comment] 2015-08-19 14:29
We have addressed this issue in #1857. Closing this.

**Closed by ismailsunni** 2015-08-19 14:29 UTC
Labels: Bug, Ready
