### ISSUE TITLE
Impact Function Wizard: Disabled "from QGIS" radiobutton.

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2285] opened 2015-08-28 15:47 UTC
# Problem
Cannot add  a hazard polygon with a point exposure. The 'already loaded in QGIS' is grayed out even though there are layers that have been loaded. The alternative is to use  'pick a hazard layer from disk', however this too is a dead end (See ticket  #2282).
![4](https://cloud.githubusercontent.com/assets/10434570/9550587/85d44412-4dac-11e5-9f24-6656168357d1.png)
![3](https://cloud.githubusercontent.com/assets/10434570/9550595/88b4ed12-4dac-11e5-8a37-e2235d9dcf77.png)
![1](https://cloud.githubusercontent.com/assets/10434570/9550573/736056e0-4dac-11e5-81c8-62239347afc2.png)
![2](https://cloud.githubusercontent.com/assets/10434570/9550578/768de076-4dac-11e5-9876-f678cd10e1b4.png)

# Data
I used test data that I saved locally so that I could test the 'layer from disk' option.

**Comment by ismailsunni** [comment] 2015-08-29 00:26
Hi @roscoeKartoza 
This is the same case as in #2278 
Short story, we do not only consider the layer geometry, but also the "unit" or the "classification".

Anyway, can you paste here the keywords layer?

**Comment by timlinux** [comment] 2015-08-29 21:40
Also note that the layer actually needs to have keywords before it is listed...maybe that is a confusing distinction we make...

**Comment by borysiasty** [comment] 2015-09-03 09:31
@timlinux - actually keywordless layers are listed too. The problem is when the keyword exists. For example, the *Classified polygon hazard on buildings* function won't work with the *Flood Polygon* sample layer because it's classified with *flood_vector_hazard_classes* while the function requires *generic_vector_hazard_classes*

**Comment by borysiasty** [comment] 2015-09-03 18:43
Fixed in PR #2323 (see also #2282)

**Closed** 2015-09-04 08:20 UTC
