### ISSUE TITLE
BUG : The Detail report is just appear No Data / 0 "zero"

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2320] opened 2015-09-03 09:16 UTC
# Problem
Based on systematic testing that I and @fredychandra doing in last week, we foud some bug. One of them is the detailed report in the result is just appear "no data" or 0 "zero".

# Detail
![selection_163](https://cloud.githubusercontent.com/assets/8871958/9654518/8006e4f6-5255-11e5-85eb-1981d606722b.png)
![selection_164](https://cloud.githubusercontent.com/assets/8871958/9654524/8369f782-5255-11e5-8f5d-6d0e3dde8739.png)

# Where is the bug found?
![selection_167](https://cloud.githubusercontent.com/assets/8871958/9654784/1903ae72-5257-11e5-92c7-6651711ff7cf.png)

For the other IF, As we are discuss with @Charlotte-Morgan, is it possible we can also hide the column that have zero in the result? So the table just show the result that have a value.
![selection_166](https://cloud.githubusercontent.com/assets/8871958/9654734/d47e5d56-5256-11e5-84d1-7d8b8b78c0c8.png)

# Proposed Solution
Make it Happy

# CC
@timlinux 

Thank you

**Comment by cchristelis** [comment] 2015-09-03 23:56
Hi @samnawi, thanks for this thorough bug report. The nan on minimum needs, I could reproduce with the test data and have made a fix https://github.com/AIFDR/inasafe/pull/2324. The other issues I could not reproduce with the test data. The only way that I could was by changing the keywords. Would it be possible to perhaps send me small clipped sections of these scenarios, so that I can see reproduce it locally.

**Comment by cchristelis** [comment] 2015-09-03 23:57
Once the nan and zero issues are sorted, I'll see to reducing the reports. An alternative way to solve our real estate issue, is to transpose the tables.

**Comment by Charlotte-Morgan** [comment] 2015-09-04 03:13
hi @cchristelis - thanks for looking at this @samnawi - will check out the changes later.
Re the idea of transposing the report - this in unlikely to work unless there are only a few areas of aggregation. In many of our real world examples the aggregation report goes for many pages.

**Comment by cchristelis** [comment] 2015-09-04 07:48
understood @Charlotte-Morgan, transposing won't be an option. Let's continue the work on removing columns with 0's etc to #2321 and focus here on the 'No Data' and false Zeroes, which in is very NB.

**Comment by timlinux** [comment] 2015-09-04 08:10
@Charlotte-Morgan sorry I never got a chance to explain why transposing would not word as I was handing over to @cchristelis / running out the door yesterday....

**Comment by cchristelis** [comment] 2015-09-04 09:52
So the more I dig the bigger this issue turns out to be. What we are seeing here is not a bug at all it is a feature. The postprocessors where built around the OSM data structure. This is not how we are expecting the client to use this, but none the less it is how it is. I've created a feature update ticket to address that: #2332

**Comment by Charlotte-Morgan** [comment] 2015-09-04 10:36
thanks @cchristelis - i think i may already have a ticket saying we need to be able to work with non osm buildings too.

**Comment by cchristelis** [comment] 2015-09-09 08:30
This has been fixed by PR https://github.com/AIFDR/inasafe/pull/2345

**Closed** 2015-09-09 08:31 UTC
Labels: Bug, In progress, Release Blocker, Reporting
