### ISSUE TITLE
Bug on the result of the Flood Impact Function in InaSAFE

### ISSUE THREAD

**Issue by harrymahar** [AIFDR/inasafe#1727] opened 2015-03-06 09:56 UTC
## Problem

I got this bug when run flood impact function for buildings. I run using buildings (Vector) as exposure data and flood (Vector) as hazard data. The hazard data that I used has attribute 'affected' which all of its values is 1 (affected). Then I got wrong output (You can see in the screenshoot) where some buildings inside the flood area still categorized as not inundated (green colour). It should be categorized as inundated (red colour). 

I re-run again using different hazard data but still vector type and its attribute 'affected' which has different values. They are 0 (not affected) and 1 (affected). In this time I got correct result with InaSAFE flood Impact function.

So I assume that there is bug for The result of Flood Impact Function in InaSAFE using hazard data (vector) and its attribute only has single value. I might be wrong but it was happened with all HOT Trainer too.

## Platform

QGIS ver 2.8.1 Wien
InaSAFE ver 3.1.0 dev-master
Windows 8.1 64 Bit

## ScreenShoot

![inasafe_bug](https://cloud.githubusercontent.com/assets/2534179/6523344/915850ae-c421-11e4-9b6a-8c717a7a9492.PNG)

![inasafe_bug2](https://cloud.githubusercontent.com/assets/2534179/6523351/9ac175c6-c421-11e4-80d8-e197dd318a0f.PNG)

**Comment by timlinux** [comment] 2015-03-09 04:57
Note this fix should be backported for a 3.0.1 release.

**Comment by cchristelis** [comment] 2015-03-17 16:05
The hazard data for the flood vector building impact function assumes there is an attribute that indicates the flooded status for each flood polygon. The impact function first looks for an attribute 'affected', after which it looks for an attribute 'FLOODPRONE'. 
The problem you encountered is because the 'affected' attribute was not found and the 'FLOODPRONE' attribute was used.
I have not been able to reproduce this under Linux using both 'affected' and 'FLOODPRONE'. The only way that I was able to reproduce is by adding some white space before the title.
When I had a column ' affected' and 'FLOODPRONE' I could re-produce this.
@harrymahar, could you please confirm that the data set that is causing the problems doesn't have any white space?
We are planning some re-work in the way the parameters are selected in #1689. I think it will make sense to let the user select the appropriate column (based on default values). 
As soon as I have access to a Windows machine I will see if I can re-produce this problem without using white-space in the column name.

**Comment by cchristelis** [comment] 2015-04-06 21:37
@timlinux it seems like this confusion could be caused by the different names for the affected field in the following impact functions:
- In flood_vector_osm_building_impact the metadata targets a field by default called 'FLOODPRONE' ('affected_field', 'FLOODPRONE').
- In flood_vector_building_impact_qgis the metadata targets a field by default called 'affected' ('affected_field', 'affected'),
It would be nice to standardize this default value. Which would you suggest the most appropriate?

**Comment by akbargumbira** [comment] 2015-04-07 03:52
hi @cchristelis, I think we can remove flood_vector_osm_building_impact in favor of flood_vector_building_impact_qgis

**Comment by cchristelis** [comment] 2015-04-07 07:31
Hi @akbargumbira, I think your proposal looks good, we should have only one. Both these IFs are very similar and only lead to user confusion.

**Comment by wulankhairunisa** [comment] 2015-04-15 08:19
Hi @cchristelis @akbargumbira, 2 days ago Adit pulled InaSAFE from GitHub. Then we tested again to run flood impact function for buildings.
I used the hazard data that has attribute 'affected' (with values: 1, NULL) and 'FLOODPRONE' (values: YES, NULL).
 
(*I) In InaSAFE keywords creation wizard, I used 'affected' field that represents flood extent as wet/dry, on the next step I classified unique values (wet=1, dry=NULL). Then in Option (in question form) I changed affected field and value into this:
![capture](https://cloud.githubusercontent.com/assets/2551072/7154515/f9be47ba-e380-11e4-8c13-60a21f084c47.PNG)
This is the result after I run it, it isn't appropriate.
![capturse](https://cloud.githubusercontent.com/assets/2551072/7154521/0e908586-e381-11e4-86fa-b174f7f02b96.PNG)

(*II) But, when I used 'FLOODPRONE' field that represents flood extent and classified unique values (wet=YES, dry=NULL), and I didn't change affected field and value in question form option,
![1](https://cloud.githubusercontent.com/assets/2551072/7154533/36bd01a6-e381-11e4-8c54-e09258f88198.PNG)
then I run it, the result is good!
![good](https://cloud.githubusercontent.com/assets/2551072/7154551/61b4a5bc-e381-11e4-996f-02ced9fe4ade.PNG)

(*III) After that, I tried to delete 'FLOODPRONE' field (leave the 'affected' field), so that the impact function doesn't look for a 'FLOODPRONE' field, the result is the same like the first trial (*I).

I've read your comments above, I assume the impact function still unable to read the field names unless a 'FLOODPRONE' that represents flood.

**Comment by lucernae** [comment] 2015-04-15 21:12
@akbargumbira @cchristelis we can disable the IF via metadata key is_disabled or just delete them. I also seen some IF like flood_raster_road_qgis and flood_raster_road_qgis_gdal handles the same hazard and exposure types. Perhaps we wanted to enable just one?

**Comment by akbargumbira** [comment] 2015-04-16 06:49
@wulankhairunisa Thank you for the very clear explanation! I am working on this and will push it for 3.1

**Comment by akbargumbira** [comment] 2015-04-29 10:38
I am closing this. @wulankhairunisa and @harrymahar please try it again with the current inasafe develop and reopen if this still happens

**Closed by akbargumbira** 2015-04-29 10:38 UTC
Labels: In progress
